print("This is Gladstone setting up a Python Code in nano")
print("This is another print statement in my Python code which I am using to test my understanding of git/github and you could also add nano. So I just corrected a few spelling errors")
print("So I copied the all the files from my thumb drive to this Project Folder and I added a .gitignore file which includes all .txt files and .pdf files. I do not expect these to be sent to Repo")
print("while in the thumb drive add a new folder with files then copied to this Project. I notice that the changes are not tracked here")
print("so I think the problem is solved. I added a README.md file in the thum drive and addd to the Project and so .gitignore did not affect the status and the README.md is recoggnised")
